app:
  chart: "simple-python-webserver"
  name: "simple-app"
  image: "simple-app:v1.0"
  pullPolicy: "Never"
  resources:
    requests:
       memory: 50Mi
       cpu: 50m
    limits:
      memory: 100Mi
      cpu: 100m
  service:
    port: "80"
    targetPort: "8080"
  env:
    SERVER_HOST: "0.0.0.0"
    SERVER_PORT: "8080"
    EMAIL_LOGIN: "test@domain.com"
    SMTP_SERVER: "smtp.gmail.com"
    SMTP_SERVER_PORT: "587"
    EMAIL_RECIEVER: "test@domai.com"
    DB_USER: "postgres"
    DB_HOST: "postgresql-headless"
    DB_PORT: "5432"
    DB_NAME: "app"
  secrets:
    EMAIL_PASSWORD: 
      valueFrom:
        secretKeyRef:
          name: emailpass
          key: emailpass
    DB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: dbpass
          key: dbpass

ingress:
  enable: "false"
  host: "example.local"

rbac:
  serviceAccount:
    name: "internal-kubectl"
  role:
    name: "modify-networking"
  roleBinding:
    name: "modify-networking"
