apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secrets.EMAIL_PASSWORD.valueFrom.secretKeyRef.key | quote }}
type: Opaque
stringData:
    emailpass: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secrets.DB_PASSWORD.valueFrom.secretKeyRef.key | quote }}
type: Opaque
stringData:
    dbpass: "test1"
