apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Values.app.chart }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.app.name | quote }}
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
